import Foundation

extension L10n {
  static let chinese: [String: String] = [
    "Your timetable, study work and learning needs, brought together.": "把课表、学习任务和需要关注的内容汇集到一起。",
    "Courses detected from your timetable": "从课表发现的课程",
    "Review once. Matching classes from these calendar sources will stay connected.": "确认一次后，这些日历来源中匹配的后续课程会自动关联。",
    "Class counts cover the next 12 weeks.": "课次数量统计未来 12 周。",
    "Connect to the saved course when unambiguous": "明确匹配时将关联到已有课程",
    "Add selected": "添加所选",
    "Add all": "全部添加",
    "Your learning contexts": "你的学习课程",
    "Start with your timetable or study material": "从课表或学习材料开始",
    "Import a timetable in Calendar or a syllabus with Smart Import. Review detected courses here.": "在日历导入课表，或用智能导入带入课程大纲，然后在这里确认发现的课程。",
    "{0} timetable entries connected": "已关联 {0} 条课表记录",
    "Other ways to add a course": "其他添加方式",
    "Course name": "课程名称",
    "Add manually": "手动添加",
    "Ignored timetable modules": "已忽略的课表模块",
    "Ignored modules stay hidden across imports and subscription refreshes.": "忽略的模块在后续导入和订阅刷新时不会反复出现。",
    "Review ignored modules again": "重新查看已忽略的模块",
    "More than one saved course matches this module. Resolve duplicate courses before accepting.": "有多门已保存课程与此模块匹配，请先处理重复课程后再确认。",
    "Course deadline": "课程截止日期",
    "Your current focus": "你设置的学习重点",
    "Previously saved topic": "之前保存的学习主题",
    "From linked study sessions": "来自已关联的学习时段",
    "From imported study material": "来自导入的学习材料",
    "Continue the work already linked to this course.": "继续完成这门课程已有的学习任务。",
    "Review: {0}": "复习：{0}",
    "This topic still needs attention.": "这个主题仍需要关注。",
    "Review your notes before the next class.": "在下节课之前回顾笔记。",
    "No available time fits this study suggestion. Adjust its duration or your availability.": "没有适合这项学习建议的空闲时间，请调整时长或可用时间。",
    "Next class": "下节课",
    "Next tutorial / lab": "下次辅导课 / 实验课",
    "This week": "本周",
    "{0} study sessions": "{0} 个学习时段",
    "Suggested next action": "建议的下一步",
    "Arrange": "安排时间",
    "Current focus": "当前学习重点",
    "A focus will emerge from your imported material or linked study sessions.": "学习重点会从导入材料或已关联的学习时段中呈现。",
    "Pending study work": "待完成的学习任务",
    "No pending study sessions linked yet.": "目前没有已关联的待完成学习时段。",
    "View all pending study work": "查看所有待学任务",
    "Review unfinished work: {0}": "回顾尚未完成的任务：{0}",
    "Nothing flagged right now.": "目前没有需要特别关注的内容。",
    "Add something to revisit": "添加需要回顾的内容",
    "Plans for this course": "这门课程的计划",
    "Make a study plan": "制定学习计划",
    "A course is the learning context. Each plan is a specific objective.": "课程提供长期学习背景；每份计划对应一个具体目标。",
    "Study material & notes": "学习材料与笔记",
    "Import study material": "导入学习材料",
    "Add note": "添加笔记",
    "Execution history": "执行记录",
    "{0} execution records · {1} actual minutes": "{0} 条执行记录 · 实际投入 {1} 分钟",
    "All classes": "全部课次",
    "Previous 4 weeks and next 12 weeks. Repeated classes are expanded locally.": "显示过去 4 周和未来 12 周的课次，重复课程在本地展开。",
    "No upcoming class found.": "暂无即将到来的课次。",
    "Assessments & deadlines": "考核与截止日期",
    "Add Assessment": "添加考核",
    "Mark complete": "标记完成",
    "Weekly timetable pattern": "每周课表规律",
    "View all classes": "查看全部课次",
    "{0} upcoming": "未来 {0} 次",
    "Accept a timetable match in Courses to connect classes.": "在课程页确认课表匹配，即可关联课次。",
    "tutorial": "辅导课",
    "seminar": "研讨课",
    "workshop": "实践课",
    "class": "课次",
    "Smart Import": "智能导入",
    "Bring in something you already have.": "把已有的内容带进来。",
    "Analysing imported content…": "正在分析导入内容…",
    "Back": "返回",
    "Detected from imported content": "从导入内容中检测到",
    "Prefer: ": "偏好：",
    "Fixed: ": "固定：",
    "Tell Intent what I meant": "告诉 Intent 我的本意",
    "Reinterpret": "重新理解",
    "Edit source": "编辑原文",
    "Import Only": "仅导入",
    "Import & Arrange": "导入并安排",
    "Import Only saves to Inbox. Arranging opens a draft; calendar time requires final confirmation.": "仅导入会保存到收件箱；安排会打开草稿，最终确认后才写入日历。",
    "Review or discard the current draft before arranging another import.": "请先查看或丢弃当前草稿，再安排新的导入计划。",
    "Paste": "粘贴",
    "Clipboard": "剪贴板",
    "File": "文件",
    "The clipboard has no text.": "剪贴板中没有文本。",
    "Paste a study plan, syllabus, task list, ChatGPT plan, email, or schedule…": "粘贴学习计划、课程大纲、任务清单、ChatGPT 计划、邮件或日程…",
    "Text interpretation sends only this content and your correction to the configured AI. Structured JSON and ICS are validated locally.": "文本解析只会将这段内容和你的修正发送给已配置的 AI。结构化 JSON 和 ICS 在本地校验。",
    "Analyse": "分析",
    "Edit detected item": "编辑检测到的项目",
    "Known duration": "已知时长",
    "Preferred day": "偏好星期",
    "Preferred time (HH:mm)": "偏好时间（HH:mm）",
    "Truly fixed appointment": "确实固定时间的安排",
    "Original date wording": "原文中的日期表述",
    "Unresolved ambiguity (clear after correction)": "尚未明确的信息（修正后清空）",
    "Save": "保存",
    "Arrange imported plan": "安排导入计划",
    "Invalid import JSON.": "导入 JSON 格式或字段无效。",
    "Resolve missing durations, deadlines and constraints before arranging.": "请先补全时长、明确截止日期与约束，再安排时间。",
    "Choose a TXT, Markdown, JSON or ICS file. PDF is not supported yet.": "请选择 TXT、Markdown、JSON 或 ICS 文件。暂不支持 PDF。",
    "Import text must be under 200 KB.": "导入文本不能为空且需小于 200 KB。",
    "Import text must be UTF-8 and under 200 KB.": "导入文本需为 UTF-8 编码且小于 200 KB。",
    "Calendar context is incomplete. Reduce the planning scope before arranging.": "日历上下文不完整，请缩小规划范围后重试。",
    "Source facts": "导入内容",
    "Supported scheduling rule": "支持的排程约束",
    "Import category: courses": "课程",
    "Import category: goals": "目标",
    "Import category: deadlines": "截止日期",
    "Import category: events": "事件",
    "Import category: sessions": "时段",
    "Import category: tasks": "任务",
    "Import category: constraints": "约束",
    "Import category: notes": "备注",
    "Import category: resources": "资源",
    "Import category: ideas": "未来想法",
    "Import category: plans": "计划",
    "courses": "课程",
    "goals": "目标",
    "deadlines": "截止日期",
    "events": "事件",
    "sessions": "时段",
    "tasks": "任务",
    "constraints": "约束",
    "notes": "备注",
    "resources": "资源",
    "ideas": "未来想法",
    "plans": "计划",
    "Edit": "编辑",
    "Session": "时段",
    "{0} · {1}": "{0} · {1}",
    "{0} · {1} · {2}": "{0} · {1} · {2}",
    "{0}:{1}": "{0}:{1}",
    "low": "低",
    "medium": "中",
    "high": "高",
    "Invalid session shape, scheduling preferences or constraint.": "时段内容、排程偏好或约束无效。",
    "The fixed session time is preserved.": "已保留固定时段的时间。",
    "The locked or fixed time is infeasible. It has not been moved; resolve the conflict or unlock it.":
      "锁定或固定的时间不可用，尚未移动。请解决冲突或先解锁。",
    "No feasible slot satisfies availability, buffers, capacity, duration, deadline and hard constraints. Change a hard boundary or split the session explicitly.":
      "没有同时满足可用时间、缓冲、容量、时长、截止日期和硬约束的时间。请调整限制，或明确拆分此时段。",
    "Inside your available hours.": "位于你的可用时间内。",
    "Clear of calendar commitments, required buffers and known travel times.":
      "避开了日历安排、必要缓冲和已知通勤时间。",
    "Finishes within the scheduling boundary.": "可在排程的截止时间内完成。",
    "Respects: {0}": "满足：{0}",
    "Preference considered: {0}": "已考虑偏好：{0}",
    "Respects preference: {0}": "满足偏好：{0}",
    "Trade-off against preference: {0}": "与偏好存在取舍：{0}",
    "Overlaps your preferred time window or is close to the preferred time.": "与偏好的时间段重叠，或接近偏好时间。",
    "Falls on a preferred day.": "位于你偏好的日期。",
    "This day has {0} minutes of existing commitments; lighter days score higher.":
      "当天已有 {0} 分钟安排；安排较少的日期得分更高。",
    "Matches an energy window you supplied.": "符合你设置的精力时段。",
    "Includes time after your preferred evening cutoff.": "部分时间超过了你偏好的晚间截止时间。",
    "Falls within your requested recovery period after training.": "位于你设置的训练后恢复时段内。",
    "At an edge of a free window, preserving an uninterrupted block.": "位于空闲时间的边缘，可保留连续的空闲时段。",
    "Splits a free window; this is included in the score.": "会拆开一段空闲时间，评分已考虑这一点。",
    "Near a calendar session explicitly linked to the same course.": "接近已明确关联到同一课程的日历时段。",
    "Uses the supplied completion evidence for this window.": "参考了该时间段已有的执行完成记录。",
    "Invalid draft.": "草稿无效。",
    "Invalid session: {0}": "时段无效：{0}",
    "Invalid planning constraint.": "规划约束无效。",
    "Impossible duration.": "该时长不可用。",
    "Impossible duration or session count.": "时长或时段数量不可用。",
    "Invalid scheduling constraint.": "排程约束无效。",
    "Invalid session timing.": "时段时间无效。",
    "Unexpected fields for operation.": "操作中包含不支持的字段。",
    "Empty update.": "更新内容为空。",
    "Malformed patch.": "更改内容格式错误。",
    "Unknown constraint value field.": "约束值中存在未知字段。",
    "Unknown scheduling property.": "存在未知排程属性。",
    "Unknown preferred window field.": "偏好时段中存在未知字段。",
    "Unknown session field.": "时段中存在未知字段。",
    "Unknown constraint field.": "约束中存在未知字段。",
    "Malformed session update.": "时段更新格式错误。",
    "Empty or oversized patch.": "更改内容为空或过大。",
    "Missing target session.": "缺少目标时段。",
    "Unlock the session explicitly before changing it.": "修改前请先解锁该时段。",
    "Missing update.": "缺少更新内容。",
    "Missing preferred start.": "缺少偏好的开始时间。",
    "Missing duration.": "缺少时长。",
    "Remove dependent sessions first.": "请先删除依赖此时段的其他时段。",
    "Invalid new session.": "新时段无效。",
    "Malformed split: preserve workload and valid chunk sizes.": "拆分格式错误：请保留总工作量，并使用有效的分段时长。",
    "Malformed merge.": "合并格式错误。",
    "Cannot merge locked, missing, or depended-on sessions.": "无法合并已锁定、不存在或被其他时段依赖的时段。",
    "Sessions in different locations cannot be merged.": "不同地点的时段不能合并。",
    "Missing priority.": "缺少优先级。",
    "Missing deadline.": "缺少截止日期。",
    "Missing constraint.": "缺少约束。",
    "A locked session would be modified indirectly. Unlock it first.": "此更改会间接修改锁定的时段，请先解锁。",
    "A preserved session conflicts with a hard scheduling rule or calendar change. Unlock or explicitly reschedule it first.":
      "保留的时段与硬性排程规则或日历更改冲突。请先解锁或明确重新安排。",
    "A prerequisite would invalidate a preserved session. Unlock or reschedule it explicitly.":
      "前置任务会使保留的时段不可行。请明确解锁或重新安排。",
    "A hard scheduling rule, calendar commitment or prerequisite changed. Replan before committing.":
      "硬性排程规则、日历安排或前置任务已变化，请重新规划后再确认。",
    "Session edited. Other sessions are preserved unless dependencies require a timing change.":
      "时段已修改。除依赖关系要求调整时间外，其他时段保持不变。",
    "Session unlocked.": "时段已解锁。",
    "Session locked. Later changes will preserve it.": "时段已锁定，后续更改会保留此安排。",
    "Priority: {0} → {1}": "优先级：{0} → {1}",
    "Added constraint: {0}": "新增约束：{0}",
    "Removed constraint: {0}": "已移除约束：{0}",
    "Reminders require the bundled Intent app. Launch the installed app to enable them.":
      "提醒需要通过完整的 Intent 应用启用。请启动已打包的 App。",
    "Abandon": "放弃",
    "abandoned": "已放弃",
    "Accepted adaptations": "已采纳的调整",
    "Alternatives": "备选时间",
    "Anything that got in the way?": "有什么影响了执行？",
    "Apply all": "全部应用",
    "Apply to draft": "应用到草稿",
    "Apply": "应用",
    "Changed in last edit": "上次编辑已修改",
    "Changes apply only to this draft. Lock sessions to keep them unchanged.":
      "更改仅应用于此草稿。锁定时段可保持其安排不变。",
    "Commit final plan": "确认并保存计划",
    "Could not save execution": "无法保存执行记录",
    "Create AI draft": "生成 AI 草稿",
    "Definition of done": "完成标准",
    "Describe the outcome. Review and edit before saving anything.": "描述你想达成的结果。保存前可先检查和修改。",
    "Details (optional)": "补充说明（可选）",
    "Disable reminders": "关闭提醒",
    "Discard draft": "丢弃草稿",
    "Dismiss": "暂不考虑",
    "Duration: {0} minutes": "时长：{0} 分钟",
    "Edit draft session": "编辑草稿时段",
    "Energy requirement": "精力需求",
    "Energy": "精力",
    "Ignore": "忽略",
    "Intent checks while running and queues eligible reminders up to 24 hours ahead. New opportunities are discovered when it next runs.":
      "Intent 运行时会检查安排，并提前安排未来 24 小时内的适用提醒。下次运行时会继续发现新的执行机会。",
    "Last edit · {0} sessions changed": "上次编辑 · 修改了 {0} 个时段",
    "Late work starts: {0}:00": "晚间时段起点：{0}:00",
    "Later": "稍后",
    "More evidence is needed before suggesting changes.": "还需要更多执行记录，才能提出可靠的调整建议。",
    "Move Friday’s session…": "把周五的时段移到……",
    "No feedback": "不填写原因",
    "Not now": "暂不填写",
    "OK": "好",
    "Observed app behavior only. Suggestions need at least five distinct sessions per area; comparisons need five per group. Repeated feedback needs three distinct sessions. Explicit preferences are kept separately.":
      "仅依据应用中的执行记录。每个领域至少需要 5 个不同时段，分组比较每组至少需要 5 个；重复反馈至少来自 3 个不同时段。你明确设置的偏好会单独保留。",
    "Optional preferences rank feasible times. They never override availability, locks or deadlines.":
      "可选偏好用于对可行时间排序，不会覆盖可用时间、锁定安排或截止日期。",
    "Optional. This helps Intent learn which plans work for you.": "选填，帮助 Intent 了解哪些计划更适合你执行。",
    "Planning Copilot": "规划助手",
    "Planning Style": "规划风格",
    "Planning Workspace": "规划工作区",
    "Planning assistance": "主动规划辅助",
    "Prefer a focus window": "优先使用专注时段",
    "Prefer to avoid late work": "尽量避免晚间工作",
    "Preferred days": "偏好的日期",
    "Preferred end: {0}:00": "偏好结束时间：{0}:00",
    "Preferred start: {0}:00": "偏好开始时间：{0}:00",
    "Priority: {0}": "优先级：{0}",
    "Quick adjustments": "快捷调整",
    "Quiet: in-app suggestions and essential session/deadline reminders. Balanced: also preparation and missed-session recovery. Proactive: also free-window and capacity nudges.":
      "安静：应用内建议及必要的时段、截止提醒。均衡：增加课前准备和错过时段的补救建议。主动：进一步提示空闲时间和工作量调整。",
    "Ranked alternatives from this scheduling pass. Recheck before moving.":
      "本次排程的备选时间，已按适合程度排序。移动前请再次确认。",
    "Reason": "原因",
    "Recovery before high-energy work after training: {0} min": "训练后开始高精力任务前的恢复时间：{0} 分钟",
    "Review Machine Learning weeks 1–3…": "复习机器学习第 1–3 周内容……",
    "SUGGESTED NEXT STEP": "建议的下一步",
    "Save draft changes": "保存草稿更改",
    "Save feedback": "保存反馈",
    "Scheduling preferences (soft)": "排程偏好（软约束）",
    "Suggested changes for next week": "下周调整建议",
    "Suggestions remain in Today with reminders off. Alerts are limited to 2/day in Quiet, 3/day in Balanced, or 5/day in Proactive, with a 3-hour or 1-hour cooldown. Nonessential alerts stay between 09:00 and 21:00.":
      "关闭提醒后，建议仍会显示在“今天”。安静模式每天最多 2 次，均衡 3 次，主动 5 次；提醒间隔分别为 3 小时或 1 小时。非必要提醒只在 09:00–21:00 发送。",
    "This session is no longer available.": "此时段已不存在。",
    "Undo last change": "撤销上次更改",
    "Updating your draft…": "正在更新草稿……",
    "Why here?": "为什么安排在这里？",
    "{0} · Accepted": "{0} · 已采纳",
    "{0}: {1}": "{0}：{1}",
    "{0} minutes · {1} sessions": "{0} 分钟 · {1} 个时段",
    "{0} sessions locked": "已锁定 {0} 个时段",
    "{0} · {1}: {2}% completed ({3} sessions)": "{0} · {1}：完成率 {2}%（{3} 个时段）",
    "{0} min · {1} energy": "{0} 分钟 · {1}精力需求",
    "https://… or webcal://…": "https://… 或 webcal://…",
    "What Intent learned this week": "本周 Intent 学到了什么",
    "Observed execution patterns": "观察到的执行规律",
    "Time of day": "一天中的时段",
    "Duration": "时长",
    "Quiet": "安静",
    "Balanced": "均衡",
    "Proactive": "主动",
    "Requesting permission…": "正在请求权限……",
    "Enable reminders…": "启用提醒……",
    "Reminders enabled.": "提醒已启用。",
    "Permission was not granted. You can change it in macOS System Settings → Notifications.":
      "尚未获得通知权限。你可以在 macOS“系统设置 → 通知”中修改。",
    "no time": "没有时间",
    "too tired": "太累了",
    "too long": "时长太长",
    "unclear how to start": "不知道如何开始",
    "priority changed": "优先级变了",
    "unexpected conflict": "临时出现冲突",
    "not important anymore": "已经不重要了",
    "other": "其他",
    "unknown": "未指定",
    "morning": "上午",
    "afternoon": "下午",
    "evening": "傍晚",
    "late night": "深夜",
    "<30m": "不足 30 分钟",
    "30–50m": "30–50 分钟",
    "51–89m": "51–89 分钟",
    "90+m": "90 分钟以上",
    "Hard": "硬约束",
    "Soft": "软约束",
    "critical": "紧急",
    "Candidate score: {0}": "候选评分：{0}",
    "Before: {0}": "修改前：{0}",
    "After: {0}": "修改后：{0}",
    "Deadline: ": "截止日期：",
    "Unlock": "解锁",
    "Lock": "锁定",
    "Locked": "已锁定",
    "Unlocked": "未锁定",
    "You": "你",
    "Copilot": "助手",
    "Absent": "无",
    " · {0} energy · {1} min · ": " · {0}精力需求 · {1} 分钟 · ",
    "Make lighter": "减轻工作量",
    "Finish sooner": "提前完成",
    "Use fewer sessions": "减少时段数量",
    "Avoid evenings": "避开晚间",
    "Keep weekend free": "周末留空",
    "Balance workload": "均衡工作量",
    "Split long sessions": "拆分较长时段",
    "Time": "时间",
    "Previous": "上一页",
    "Next": "下一页",
    "Create a session at {0}:00": "在 {0}:00 创建时段",
    "Your planned {0}-minute session starts at {1}.": "计划中的 {0} 分钟时段将于 {1} 开始。",
    "Make {0} easier to start": "让“{0}”更容易开始",
    "This is {0} minutes; your current session limit is {1} minutes.":
      "此时段长 {0} 分钟；你当前的单次时长上限是 {1} 分钟。",
    "Review session": "查看时段",
    "A window for {0}": "有时间执行“{0}”",
    "There is room for this {0}-minute session in your available time.": "当前空闲时间可以安排这个 {0} 分钟的时段。",
    "Find a new time for {0}": "为“{0}”重新找个时间",
    "You skipped this session. These windows fit its duration.": "你跳过了此时段。以下空闲时间可以容纳它。",
    "The planned time passed without completion. These windows fit its duration.":
      "原定时间已过，此时段尚未完成。以下空闲时间可以容纳它。",
    "Move": "移动",
    "Prepare for {0}": "为“{0}”做准备",
    "{0} is at {1}. {2} is marked {3}.": "{0} 将于 {1} 开始。{2} 的掌握程度为“{3}”。",
    "Plan a 30-minute review": "安排 30 分钟复习",
    "Review {0}": "复习“{0}”",
    "This linked course session has finished. Capture what needs another look.":
      "关联的课程已结束。记录需要再次复习的内容。",
    "Plan a review": "安排复习",
    "Deadline: {0}": "截止事项：{0}",
    "Due {0}. Check that the remaining work has time allocated.": "截止时间为 {0}。请确认已为剩余任务预留时间。",
    "Review obligation": "查看待办事项",
    "Today exceeds your capacity": "今天的安排超出容量",
    "{0} planned minutes exceed your {1}-minute daily limit.": "已安排 {0} 分钟，超过你每天 {1} 分钟的上限。",
    "Review today": "查看今天的安排",
    "Try difficult work earlier": "尝试把高难度任务安排得更早",
    "Review adaptation": "查看调整建议",
    "Make {0} actionable": "把“{0}”变成可执行的行动",
    "This Inbox item has not yet become an executable next step.": "此收件箱事项尚未转为可执行的下一步。",
    "{0} {1} in Intent.": "{0} 请在 Intent 中{1}。",
    "Cap future {0} sessions at 50 minutes?": "将以后的{0}时段上限设为 50 分钟？",
    "Increase future {0} estimates by {1}%?": "将以后的{0}预计时长增加 {1}%？",
    "Include a concrete first action in future {0} sessions?": "为以后的{0}时段添加具体的第一步？",
    "Prefer lower-energy {0} work after 21:00?": "21:00 后优先安排低精力需求的{0}任务？",
    "{0}: 30–50m sessions completed {1}% of the time (n={2}), versus {3}% for 90+m (n={4}).":
      "{0}：30–50 分钟时段的完成率为 {1}%（{2} 次），90 分钟以上时段为 {3}%（{4} 次）。",
    "{0}: ‘too long’ was reported across {1} distinct sessions.": "{0}：在 {1} 个不同时段中反馈了“时长太长”。",
    "{0} took {1}% longer than estimated.": "{0}的实际用时比预计多 {1}%。",
    "{0}: unclear how to start was reported across at least three sessions.":
      "{0}：至少 3 个不同时段反馈了“不知道如何开始”。",
    "{0}: high-energy work after 21:00 completed in {1}% of {2} sessions.":
      "{0}：21:00 后的高精力任务完成率为 {1}%（共 {2} 个时段）。",
    "Next fixed commitment": "下一个固定安排",
    "Needs attention": "需要关注",
    "Deadline: {0} · {1}": "截止事项：{0} · {1}",
    "Overdue task: {0}": "逾期任务：{0}",
    "{0} recent intentions to process": "{0} 条近期想法待处理",
    "Some records could not fit in this snapshot. Free capacity is unavailable.":
      "部分记录超出快照范围，暂时无法确定空闲容量。",
    "Date": "日期",
    "Inbox": "收件箱",
    "Courses": "课程",
    "Capture first, decide later": "先记录，再决定",
    "Put it here. You don't need a plan yet.": "先把想法放在这里，不必马上制定计划。",
    "What's on your mind?": "有什么想做的事？",
    "Add details": "添加详情",
    "Optional note": "备注（可选）",
    "Status": "状态",
    "Saved items": "已存事项",
    "Nothing waiting here": "这里暂无待处理事项",
    "Capture an intention above, or find existing tasks and notes in Saved items.":
      "在上方记录想法，或从“已存事项”查看原有任务和笔记。",
    "Context": "领域 / 情境",
    "Plan this": "规划这件事",
    "Convert to task": "转为任务",
    "Make a goal": "转为目标",
    "Create draft plan": "创建计划草稿",
    "Someday": "以后再说",
    "Archive": "归档",
    "Restore to Inbox": "恢复到收件箱",
    "Details": "详情",
    "Has a deadline": "设有截止日期",
    "Deadline": "截止日期",
    "Create deadline task": "创建带截止日期的任务",
    "Save details": "保存详情",
    "unprocessed": "待处理",
    "someday": "以后再说",
    "processed": "已处理",
    "archived": "已归档",
    "intention": "想法",
    "task": "任务",
    "goal": "目标",
    "plan": "计划",
    "idea": "灵感",
    "deadline": "有截止日期",
    "Active": "进行中",
    "Drafts": "草稿",
    "Agenda": "日程",
    "Day": "日",
    "Week": "周",
    "Review in Calendar": "在日历中查看",
    "Review draft": "查看草稿",
    "Learning in context": "联系实际的学习",
    "Classes, topics and knowledge gaps, in one place.": "在同一处查看课堂、主题和知识盲点。",
    "Your courses live here": "课程都在这里",
    "Add a course, then link its classes and knowledge gaps.": "添加课程，再关联课堂与知识盲点。",
    "NEXT": "下一步",
    "Nothing else scheduled right now": "目前没有其他安排",
    "Leave some space, or choose an intention from your Inbox.": "留一些空闲，或从收件箱选择一件想做的事。",
    "Open Inbox": "打开收件箱",
    "What changed": "需要调整",
    "Later today": "今天稍后",
    "{0} min of flexible capacity": "剩余灵活时间：{0} 分钟",
    "The rest of your day is open.": "今天剩余时间暂无安排。",
    "{0} needs a new time. Open Calendar to adjust it.": "「{0}」需要重新安排时间，可打开日历调整。",
    "A draft is waiting for your review in Calendar.": "日历中有一份草稿等待你确认。",
    "All day": "全天",
    "AI draft · not confirmed": "AI 草案 · 未确认",
    "Review": "查看",
    "Calendar view": "日历视图",
    "Confirmed session": "已确认时段",
    "Some draft sessions have no time yet. Review the plan to adjust them.":
      "部分草案时段尚无可用时间，请打开计划进行调整。",
    "Week grid is not available yet": "周时间网格尚未实现",
    "Use Agenda for the next seven days, or Day for one date.": "可使用“日程”查看未来七天，或使用“日”查看单日安排。",
    "Show Agenda": "查看日程",
    "Inbox · {0}": "收件箱 · {0}",
    "Keep the outcome in view. Take the next step when you're ready.": "围绕目标，在准备好时迈出下一步。",
    "All contexts": "全部领域",
    "No plans in this view": "此视图暂无计划",
    "Start in Inbox, or use ⌘K when you want help shaping a plan.": "从收件箱开始，或按 ⌘K 获取规划帮助。",
    "A draft outcome. Add its first session when you're ready.": "这是计划草稿，准备好后可添加第一个时段。",
    "Sessions without a plan": "未关联计划的时段",

    "Today": "今天",
    "Calendar": "日历",
    "Tasks": "任务",
    "Plans": "计划",
    "Notes": "笔记",
    "Insights": "洞察",
    "Weekly Review": "每周回顾",
    "Weekly review": "每周回顾",
    "Settings": "设置",
    "Study": "学习",
    "Training": "运动",
    "Meals": "饮食",
    "Life": "生活",
    "Travel": "旅行",
    "Must": "必须",
    "Should": "应当",
    "Optional": "可选",
    "Weak": "薄弱",
    "Developing": "学习中",
    "Strong": "熟练",
    "planned": "待执行",
    "complete": "已完成",
    "partial": "部分完成",
    "skip": "已跳过",
    "postponed": "已推迟",
    "lecture": "讲座",
    "lab": "实验课",
    "Intention → execution": "从想法到行动",
    "Cancel": "取消",
    "Describe the outcome you want. You’ll review every session before anything is saved.":
      "描述你希望实现的目标。保存前，你可以逐一查看所有安排。",
    "Review Machine Learning weeks 1–3 next week…": "下周复习机器学习第 1–3 周的内容……",
    "Schedule from": "开始安排时间",
    "Area": "领域",
    "Building a concrete plan…": "正在制定可执行计划……",
    "{0}m": "{0} 分钟",
    "Done: {0}": "完成标准：{0}",
    "Recalculate schedule": "重新安排时间",
    "Accept {0} sessions": "确认 {0} 个时段",
    "Calendar details are shared only for sources with AI access enabled.":
      "仅向 AI 提供已开启 AI 访问权限的日历详情。",
    "Generate plan": "生成计划",
    "Planning API": "规划 API",
    "API key": "API 密钥",
    "Response text path": "响应文本路径",
    "Save key to Keychain": "将密钥保存到钥匙串",
    "Requests use the supplied API contract. The response path was verified against a live response. Keys are never stored in the database.":
      "请求遵循提供的 API 规范，响应路径已通过实际请求验证。密钥不会存入数据库。",
    "Availability & capacity": "可用时间与每日容量",
    "Day starts: {0}:00": "每日开始：{0}:00",
    "Day ends: {0}:00": "每日结束：{0}:00",
    "Daily capacity: {0} min": "每日容量：{0} 分钟",
    "Maximum session: {0} min": "单次时段上限：{0} 分钟",
    "Break: {0} min": "休息间隔：{0} 分钟",
    "Patterns from your own records. No scores, streaks, or guesswork.":
      "从真实执行记录中发现规律，不打分，不计算连续打卡，也不做主观猜测。",
    "Sessions completed": "已完成时段",
    "Execution rate": "执行率",
    "Estimation difference": "预估偏差",
    "Actual time": "实际用时",
    "{0} min": "{0} 分钟",
    "Postponements": "推迟次数",
    "Skipped": "已跳过",
    "Your patterns will emerge": "逐步了解你的执行习惯",
    "Complete sessions and record actual time to see useful insights.": "完成时段并记录实际用时，即可查看有价值的洞察。",
    "Where your time went": "时间分配",
    "Estimation difference compares completed-session estimates with recorded actual time. Positive means work took longer than estimated.":
      "预估偏差比较已完成时段的预计用时与实际用时，正值表示实际用时更长。",
    "{0} has been postponed {1} times. Consider reducing scope or changing its time.":
      "「{0}」已推迟 {1} 次，可以考虑缩小范围或调整时间。",
    "What will you change next week?": "下周你准备做哪些调整？",
    "Reflect & adapt": "回顾与调整",
    "Learn from your execution": "从执行中学习",
    "Review saved": "回顾已保存",
    "Save reflection": "保存回顾",
    "Minutes": "分钟",
    "Capture": "记录",
    "Capture the small things. Turn deeper work into sessions.": "随手记录小事，将需要专注的工作安排为时段。",
    "Add a concrete action…": "添加一项具体行动……",
    "Add": "添加",
    "Nothing loose to hold": "没有待处理事项",
    "Capture a task here, or use ⌘K to build a plan.": "在此记录任务，或按 ⌘K 制定计划。",
    "Make session": "转为时段",
    "Session created": "已创建时段",
    "Outcomes, made actionable": "让目标可以执行",
    "A goal becomes a plan. A plan becomes meaningful sessions.": "将目标转为计划，再将计划落实为有意义的时段。",
    "Start with an intention": "从一个想法开始",
    "Press ⌘K to describe a goal and review an executable plan.": "按 ⌘K 描述目标，并查看生成的可执行计划。",
    "Untitled note": "未命名笔记",
    "Thoughts that lead somewhere": "让想法有所进展",
    "Create a note. Capture questions, observations, and next actions.": "新建笔记，记录问题、观察和下一步行动。",
    "Title": "标题",
    "Capture knowledge gap": "记录知识盲点",
    "Link course": "关联课程",
    "None": "无",
    "Task captured": "任务已记录",
    "Convert note to task": "将笔记转为任务",
    "Area of life": "生活领域",
    "Add a course": "添加一门课程",
    "Add course": "添加课程",
    "Make space for {0}": "为{0}留出时间",
    "Use ⌘K to create a plan, or add a session from Today.": "按 ⌘K 创建计划，或从“今天”添加时段。",
    "Connect classes, deliberate practice, and the gaps you want to close.":
      "将课堂、刻意练习和需要弥补的知识盲点关联起来。",
    "Make a realistic plan for this part of your life.": "为生活的这一部分制定切实可行的计划。",
    "Done": "完成",
    "Current topic": "当前主题",
    "Assessment / outcome": "考核 / 目标成果",
    "Linked classes": "已关联课堂",
    "Link a calendar event": "关联日历事件",
    "Knowledge gaps": "知识盲点",
    "Topic to work on": "需要学习的主题",
    "Search results": "搜索结果",
    "No matches": "没有匹配结果",
    "Try a course, session, plan, or note title.": "尝试搜索课程、时段、计划或笔记标题。",
    "Removed event": "事件已移除",
    "Task · {0}": "任务 · {0}",
    "Plan · {0}": "计划 · {0}",
    "Note · {0}": "笔记 · {0}",
    "Course · {0}": "课程 · {0}",
    "Goal · {0}": "目标 · {0}",
    "Event · {0}": "事件 · {0}",
    "Session · {0}": "时段 · {0}",
    "Your time, made visible": "让时间安排一目了然",
    "Fixed commitments and flexible sessions, together.": "统一查看固定日程与灵活时段。",
    "Week of": "起始日期",
    "Add session": "添加时段",
    "Import .ics": "导入 .ics",
    "Open space": "空闲时间",
    "Fixed": "固定",
    "Calendar sources": "日历来源",
    "Calendar name": "日历名称",
    "Subscribe": "订阅",
    "Syncing calendar…": "正在同步日历……",
    "Drop an .ics file anywhere on this page to preview it. Subscription refresh is manual in V1.":
      "将 .ics 文件拖到此页面即可预览。V1 版本需要手动刷新订阅。",
    "Review calendar import": "预览日历导入",
    "Target calendar": "目标日历",
    "New imported calendar": "新建导入日历",
    "Import events": "导入事件",
    "Calendar must be UTF-8 and under 10 MB.": "日历文件必须采用 UTF-8 编码，且小于 10 MB。",
    "Refresh": "刷新",
    "Remove": "移除",
    "Visible": "显示",
    "Busy time": "计为忙碌时间",
    "Allow AI context": "允许 AI 读取",
    "Synced {0}": "同步于 {0}",
    "Remove this source and its imported events?": "移除此来源及其导入的事件？",
    "Remove source": "移除来源",
    "Imported calendar": "导入的日历",
    "Make room for what matters.": "为重要的事留出时间。",
    "A clear plan. One meaningful session at a time.": "清晰规划，一次专注做好一件事。",
    "Completed": "已完成",
    "Planned focus": "已安排专注时间",
    "{0}h {1}m": "{0} 小时 {1} 分钟",
    "Capacity remaining": "剩余容量",
    "Today exceeds your capacity. Move a session or reduce its scope.": "今天的安排超出容量，可以移动时段或缩小任务范围。",
    "UP NEXT": "接下来",
    "Start session": "开始时段",
    "{0} minutes · {1}": "{0} 分钟 · {1}",
    "Space for a fresh intention": "为新想法留出空间",
    "Use ⌘K to turn an intention into an executable plan, or add a session below.":
      "按 ⌘K 将想法转为可执行计划，或在下方添加时段。",
    "Your day": "今日安排",
    "{0} · {1} min · {2}": "{0} · {1} 分钟 · {2}",
    "Open": "打开",
    "Edit / reschedule": "编辑 / 重新安排",
    "Tomorrow": "明天",
    "Later this week": "本周晚些时候",
    "Skip": "跳过",
    "Purpose": "目的",
    "Done means": "完成标准",
    "Actions (one per line)": "行动清单（每行一项）",
    "Priority": "优先级",
    "{0} minutes": "{0} 分钟",
    "Schedule": "安排时间",
    "Start": "开始",
    "Save session": "保存时段",
    "Focus session": "专注时段",
    "Session notes or follow-up thoughts": "时段笔记或后续想法",
    "Save as note": "保存为笔记",
    "Create follow-up task": "创建后续任务",
    "Actual time: {0} min (0 uses timer)": "实际用时：{0} 分钟（0 表示使用计时结果）",
    "Close": "关闭",
    "Partial": "部分完成",
    "Complete": "完成",
    "Create a meaningful session": "创建一个有意义的时段",
    "Adjust session": "调整时段",
    "Define your completion criteria in Edit session.": "请在“编辑时段”中定义完成标准。",
    "Anytime": "随时",
    "Unscheduled": "未安排",
    "Unable to open your planner": "无法打开规划数据",
    "Unknown persistence error": "未知的数据存储错误",
    "WORKSPACE": "工作空间",
    "AREAS": "领域",
    "Make a plan": "制定计划",
    "Plan with AI": "AI 规划",
    "Search your workspace": "搜索工作空间",
    "Today · {0} / {1}": "今天 · {0} / {1}",
    "No sessions scheduled": "暂无已安排时段",
    "Enter a key before saving.": "请先输入密钥再保存。",
    "Could not update the credential in Keychain.": "无法更新钥匙串中的密钥。",
    "Could not save the credential in Keychain.": "无法将密钥保存到钥匙串。",
    "Use an HTTPS or WebCal calendar URL.": "请使用 HTTPS 或 WebCal 日历地址。",
    "The subscription did not return a valid calendar under 10 MB.": "订阅未返回小于 10 MB 的有效日历。",
    "Invalid title, priority, or session count.": "标题、优先级或时段数量无效。",
    "Invalid session or dependencies: {0}": "时段或依赖关系无效：{0}",
    "Session durations must match the total estimate.": "时段时长之和必须与预计总用时一致。",
    "Response is not UTF-8.": "响应不是 UTF-8 编码。",
    "The planning response is incomplete or invalid JSON: {0}": "规划响应不完整或 JSON 无效：{0}",
    "Missing HTTP response.": "缺少 HTTP 响应。",
    "The configured response text path is absent from the API response.": "API 响应中不存在配置的文本路径。",
    "The response path must identify a string containing the plan JSON.": "响应路径必须指向包含计划 JSON 的字符串。",
    "This file is not an iCalendar calendar.": "此文件不是 iCalendar 日历。",
    "More detail is needed.": "需要提供更多细节。",
    "Authentication failed. Check your API key in Settings.": "认证失败，请在设置中检查 API 密钥。",
    "The API rate limit was reached. Try again later.": "已达到 API 请求频率限制，请稍后重试。",
    "The API returned HTTP {0}.": "API 返回 HTTP {0}。",
    "Set an API key and a documented response text path in Settings.": "请在设置中填写 API 密钥和已确认的响应文本路径。",
    "Calendar changed. Recalculate the schedule before accepting.": "日历已发生变化，请重新计算时间安排后再确认。",
    "Credential saved.": "密钥已保存。",
    "Exceeds maximum focus length. Split this session or adjust Settings.":
      "超出单次专注时长上限，请拆分时段或调整设置。",
    "A prerequisite has no available slot.": "前置时段没有可用时间。",
    "No slot within capacity and deadline. Adjust the plan or availability.":
      "在容量和截止日期限制内找不到可用时段，请调整计划或可用时间。",
    "An event without a valid UID or DTSTART was skipped.": "已跳过缺少有效 UID 或 DTSTART 的事件。",
    "Invalid duration for {0}.": "事件 {0} 的时长无效。",
    "Unsupported recurrence for {0}; only its original occurrence will be shown.":
      "不支持事件「{0}」的重复规则，仅显示最初的一次。",
    "DURATION is not supported; verify the default end time for {0}.":
      "不支持 DURATION，请检查事件 {0} 的默认结束时间。",
    "Untitled event": "未命名事件",
    "Starts in 5 minutes · {0} min": "5 分钟后开始 · {0} 分钟",
    "Language": "语言",
    "App language": "应用语言",
    "Follow system": "跟随系统",
    "Language changes apply immediately. Your existing content stays unchanged.":
      "切换语言立即生效，已有内容保持原文。",
  ]
}
